apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-bot
  namespace: default
  labels:
    app: random-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-bot
  template:
    metadata:
      labels:
        app: random-bot
    spec:
      containers:
      - name: random-bot
        image: docin82/random-bot:latest
        imagePullPolicy: Always
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: random-bot-token
              key: BOT_TOKEN
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
